name: CI Pipeline Dev
on:
  push:
    branches: [ dev ]
env:
  IMAGE_NAME: intranet-newdeal
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:dev .
      - name: Push
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:dev